### ISSUE TITLE
Product-cards

### ISSUE THREAD

**Issue by rafaelstrehler** [OneBit-Software/PizzaGustav#2]
Product-cards with properties to add more or less to the order

# example
![image](https://user-images.githubusercontent.com/32476431/36545083-5de91532-17e8-11e8-87fc-f7b3025c282f.png)

**Comment by rafaelstrehler** [comment]
Important: Picture has no priority and can be released later

**Comment by Gnuelch** [comment]
Done with cfa8c0ffb0ec39a794b3a6c9f9be65e551fbcd22

Syntax:

```xml
<ShopItem name="Prosciutto" price={1050} icon={Images.test2} />
```
Note:
 - The price is in rp, as floating point values can end up with rounding errors.
 - Icon can be set in various ways:
   - `icon={{uri: "http://www.url.ch/img.bmp"}}`
   - `icon="http://www.url.ch/img.bmp"`
   - `icon={ require("../assets/img/test.bmp") }`
