### ISSUE TITLE
Side-navigtion

### ISSUE THREAD

**Issue by rafaelstrehler** [OneBit-Software/PizzaGustav#3]
On click on top-left-navigation-button (three stripes) slide in the side-navigation

# Mock-up
![app-menu](https://user-images.githubusercontent.com/32476431/36544932-faea8e02-17e7-11e8-9bb7-37006f20b7a2.png)

**Comment by Gnuelch** [comment]
reference project:
https://github.com/reactazteam/PushyHorizontalMenu

**Comment by Gnuelch** [comment]
Actual project for use
https://github.com/ilansas/react-native-navigation-drawer

**Comment by Gnuelch** [comment]
IMPORTANT
https://github.com/npm/npm/issues/18380#issuecomment-326813399

**Comment by Gnuelch** [comment]
After exhaustive testing i couldn't get ilansas' project to work. however, i found that react-navigation actually seems to have a built-in drawer component. i will need to refactor for a while to get that to work tho. [Official Documentation](https://reactnavigation.org/docs/drawer-navigator.html)
I missed this as they changed their [PERMALINKS](https://reactnavigation.org/docs/navigators/drawer) at some point. don't ask why they didn't even add a redirection to the new url.

**Comment by rafaelstrehler** [comment]
Is there any progress in the last few days?

**Comment by Gnuelch** [comment]
Got the layout set up, should work now, however i need to test how to hide specific pages while displaying others.
Almost done.

**Comment by Gnuelch** [comment]
Functionality is complete.
Only styling is left.

**Comment by Gnuelch** [comment]
Done with 7efecaacd2c19d5da2445128d5ceec71cde93030
