### ISSUE TITLE
Create start-menu

### ISSUE THREAD

**Issue by rafaelstrehler** [OneBit-Software/PizzaGustav#9]
Mockup:
![app-startseite2](https://user-images.githubusercontent.com/32476431/37464532-e7c64d26-2858-11e8-91ae-c789a07e586f.png)

**Comment by Gnuelch** [comment]
All that's left is the logo and the links to the last 3 pages (news, öffnungszeiten, kontakt)

**Comment by Gnuelch** [comment]
Completed with 49c9ff6627afadc0d98ac696c76102ddcadd0a55
